Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2020-07, with the labels that each got.

#39 CSD-182 Used flag module to provide a way for users to favorite opportunities
  cardinal_service_profile.inc
  composer.json
  config/sync/block.block.cardinal_service_pagetitle.yml
  config/sync/block.block.cardinal_service_search.yml
  config/sync/block.block.cardinal_service_user_links.yml
  config/sync/core.entity_form_display.user.user.authenticated_edit.yml
  config/sync/core.entity_form_display.user.user.default.yml
  config/sync/core.entity_form_mode.user.authenticated_edit.yml
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  config/sync/core.entity_view_display.node.su_opportunity.su_opportunities_views_result.yml
  config/sync/core.entity_view_display.user.user.default.yml
  config/sync/core.extension.yml
  config/sync/core.menu.static_menu_link_overrides.yml
  config/sync/field.field.user.user.su_user_class_year.yml
  config/sync/field.field.user.user.su_user_graduate.yml
  config/sync/field.field.user.user.su_user_org_leader.yml
  config/sync/field.storage.user.su_user_class_year.yml
  config/sync/field.storage.user.su_user_graduate.yml
  config/sync/field.storage.user.su_user_org_leader.yml
  config/sync/flag.flag.cs_favorites.yml
  config/sync/page_manager.page.saved_opportunities.yml
  config/sync/page_manager.page_variant.saved_opportunities-layout_builder-0.yml
  config/sync/pathauto.pattern.users.yml
  config/sync/system.action.flag_action.cs_favorites_flag.yml
  config/sync/system.action.flag_action.cs_favorites_unflag.yml
  config/sync/system.action.flag_delete_flagging.yml
  config/sync/ultimate_cron.job.scheduler_cron.yml
  config/sync/ultimate_cron.job.search_api_cron.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.contributor.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.su_opportunities.yml
  modules/cardinal_service_blocks/src/Plugin/Block/UserLinksBlock.php
  modules/cardinal_service_blocks/tests/src/Kernel/Plugin/Block/UserLinksBlockTest.php
  tests/codeception/functional/OpportunitiesFavoritesCest.php
  tests/codeception/functional/OpportunitiesFilterCest.php
  themes/cardinal_service/cardinal_service.theme
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/ckeditor.css
  themes/cardinal_service/dist/css/components/minimal-card/minimal_card.css
  themes/cardinal_service/dist/css/components/mission-statement/mission_statement.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.ui_patterns.yml
  themes/cardinal_service/lib/scss/base.scss
  themes/cardinal_service/package-lock.json
Labels: size/l

#60 Simplified composer dependencies
  cardinal_service_profile.post_update.php
  cardinal_service_profile.profile
  composer.json
  config/sync/migrate_plus.migration.solo_opportunities.yml
  config/sync/migrate_plus.migration_group.courses.yml
Labels: size/s

#59 CSD-238 Built minimal card paragraph type
  config/sync/core.entity_form_display.paragraph.su_minimal_card.default.yml
  config/sync/core.entity_view_display.paragraph.su_minimal_card.default.yml
  config/sync/field.field.paragraph.su_minimal_card.su_minimal_card_image.yml
  config/sync/field.field.paragraph.su_minimal_card.su_minimal_card_link.yml
  config/sync/field.storage.paragraph.su_minimal_card_image.yml
  config/sync/field.storage.paragraph.su_minimal_card_link.yml
  config/sync/paragraphs.paragraphs_type.su_minimal_card.yml
  tests/codeception/acceptance/Paragraphs/MinimalCardCest.php
  themes/cardinal_service/lib/components/minimal-card/minimal_card.html.twig
Labels: size/s

#62 Updates from stanford_profile
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/config_pages.type.stanford_events_importer.yml
  config/sync/config_pages.type.stanford_local_footer.yml
  config/sync/config_pages.type.stanford_person_importer.yml
  config/sync/config_pages.type.stanford_saml.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_url.yml
  config/sync/migrate_plus.migration.solo_opportunities.yml
  config/sync/views.view.media.yml
  config/sync/views.view.stanford_event_series.yml
  config/sync/views.view.stanford_events.yml
  config/sync/views.view.stanford_person_terms.yml
  src/Plugin/HelpSection/ProfileHelpSection.php
  src/Plugin/HelpSection/ProfileResourceSection.php
  tests/codeception/acceptance/LocalFooterCest.php
  tests/codeception/acceptance/Users/RolesCest.php
  tests/src/Unit/Plugin/HelpSection/ProfileResourceSectionTest.php
Labels: size/l

#61 CSD-237 Add CSV Importer module with some downloadable templates
  composer.json
  config/sync/core.entity_form_display.node.stanford_news.default.yml
  config/sync/core.extension.yml
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.info.yml
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.module
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.routing.yml
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.services.yml
  modules/cardinal_service_profile_helper/src/Controller/NodeCsvTemplate.php
  modules/cardinal_service_profile_helper/src/Routing/RouteSubscriber.php
  modules/cardinal_service_profile_helper/tests/src/Kernel/Controller/NodeCsvTemplateTest.php
  modules/cardinal_service_profile_helper/tests/src/Kernel/Routing/RouteSubscriberTest.php
Labels: size/s

#58 CSD-183 Style favoriting experience
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.ui_patterns.yml
  themes/cardinal_service/lib/scss/base.scss
  themes/cardinal_service/lib/scss/favorite/_dashboard.scss
  themes/cardinal_service/lib/scss/favorite/_flag.scss
  themes/cardinal_service/lib/scss/favorite/_user-links.scss
  themes/cardinal_service/lib/scss/favorite/index.scss
Labels: size/s

#65 CSD-248 Add aria-labelledby to resolve accessibility issue
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/src/Components/SelectList.jsx
Labels: size/xs

#67 removed better normalizers
  cardinal_service_profile.info.yml
  config/sync/core.extension.yml
Labels: size/xs

#66 CSD-224 Add fields and view for resources tagging
  composer.json
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/core.entity_form_display.paragraph.stanford_resource_list.default.yml
  config/sync/core.entity_form_display.taxonomy_term.cs_resource_audience.default.yml
  config/sync/core.entity_form_display.taxonomy_term.cs_resource_type.default.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.paragraph.stanford_resource_list.default.yml
  config/sync/core.entity_view_display.taxonomy_term.cs_resource_type.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.stanford_page.su_page_resource_audience.yml
  config/sync/field.field.node.stanford_page.su_page_resource_dimension.yml
  config/sync/field.field.node.stanford_page.su_page_resource_icon.yml
  config/sync/field.field.node.stanford_page.su_page_resource_type.yml
  config/sync/field.field.paragraph.stanford_resource_list.su_resource_list.yml
  config/sync/field.field.taxonomy_term.cs_resource_type.su_resource_type_icon.yml
  config/sync/field.storage.node.su_page_resource_audience.yml
  config/sync/field.storage.node.su_page_resource_dimension.yml
  config/sync/field.storage.node.su_page_resource_icon.yml
  config/sync/field.storage.node.su_page_resource_type.yml
  config/sync/field.storage.paragraph.su_resource_list.yml
  config/sync/field.storage.taxonomy_term.su_resource_type_icon.yml
  config/sync/paragraphs.paragraphs_type.stanford_resource_list.yml
  config/sync/taxonomy.vocabulary.cs_resource_audience.yml
  config/sync/taxonomy.vocabulary.cs_resource_type.yml
  config/sync/views.view.cs_resources.yml
  tests/codeception/functional/BasicPage/ResourcesCest.php
Labels: size/l

#70 CSD-268 Events Importer
  config/sync/migrate_plus.migration.cs_events_importer.yml
Labels: size/s

#69 CSD-272 Added aria-labelledby to AutoComplete component
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/src/Components/SelectList.jsx
Labels: size/xs
