Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2020-10, with the labels that each got.

#147 Updates from stanford_profile
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.extension.yml
  config/sync/dropzonejs.settings.yml
  config/sync/extlink.settings.yml
  config/sync/react_paragraphs.paragraphs_row_type.node_stanford_page_row.yml
  config/sync/syslog.settings.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.stanford_person_list_terms_first.yml
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/Media/MediaFormsCest.php
  tests/codeception/acceptance/Users/RolesCest.php
  tests/codeception/functional/Users/RolesCest.php
Labels: backend, size/s

#148 8.1.8
  CHANGELOG.md
  cardinal_service_profile.info.yml
  composer.json
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.extension.yml
  config/sync/dropzonejs.settings.yml
  config/sync/extlink.settings.yml
  config/sync/migrate_plus.migration.csv_opportunities.yml
  config/sync/react_paragraphs.paragraphs_row_type.node_stanford_page_row.yml
  config/sync/syslog.settings.yml
  config/sync/views.view.stanford_news.yml
  config/sync/views.view.stanford_person.yml
  config/sync/views.view.stanford_person_list_terms_first.yml
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/Media/MediaFormsCest.php
  tests/codeception/acceptance/Users/RolesCest.php
  tests/codeception/functional/Users/RolesCest.php
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/favorite/_user-links.scss
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_homepage/src/styles.scss
Labels: backend, frontend, patch, size/m

#150 8.1.9
  CHANGELOG.md
  cardinal_service_profile.info.yml
  composer.json
  config/sync/migrate_plus.migration.solo_opportunities.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
Labels: frontend, patch, size/xs
