Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2020-06, with the labels that each got.

#46 CSD-40 Implement tickets from opportunities filter accessibility review
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/src/Components/Filters.jsx
Labels: size/m

#56 CSD-000 Fixed opportunity row twig template conditional statements
  tests/codeception/functional/OpportunitiesFilterCest.php
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
Labels: size/xs

#57 Updates from stanford_profile
  .circleci/config.yml
  cardinal_service_profile.profile
  cardinal_service_profile.services.yml
  composer.json
  config/sync/config_ignore.settings.yml
  config/sync/core.entity_view_display.node.stanford_person.default.yml
  config/sync/core.extension.yml
  config/sync/field.field.node.stanford_person.su_person_first_name.yml
  config/sync/field.field.node.stanford_person.su_person_last_name.yml
  config/sync/field.field.node.stanford_person.su_person_photo.yml
  config/sync/field.field.node.stanford_person.su_person_short_title.yml
  config/sync/field.storage.node.su_person_first_name.yml
  config/sync/field.storage.node.su_person_full_title.yml
  config/sync/field.storage.node.su_person_last_name.yml
  config/sync/field.storage.node.su_person_photo.yml
  config/sync/views.view.stanford_news.yml
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.layout.stanford_page.full.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.node.stanford_page.css
  modules/stanford_profile_styles/dist/css/stanford_profile_styles.react_paragraphs.css
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.layout.full-width.scss
  modules/stanford_profile_styles/lib/scss/node-types/stanford_page.scss
  modules/stanford_profile_styles/lib/scss/paragraph-types/react_paragraphs/_multirow.scss
  src/Config/ConfigOverrides.php
  tests/behat/assets/documents/test.php
  tests/behat/features/BasicPage.feature
  tests/behat/features/DefaultContent.feature
  tests/behat/features/LocalFooter.feature
  tests/behat/features/Paragraphs/Banner.feature
  tests/behat/features/Paragraphs/Issue2901390.feature
  tests/behat/features/Paragraphs/MediaWithCaption.feature
  tests/behat/features/Paragraphs/WYSIWYG.feature
  tests/behat/features/SystemSiteConfig.feature
  tests/behat/features/TextFormats.feature
  tests/behat/features/Users/DefaultUsers.feature
  tests/behat/features/Users/Roles.feature
  tests/behat/features/contrib/config_readonly.feature
  tests/codeception/acceptance/Content/BasicPageCest.php
  tests/codeception/acceptance/Content/DefaultContentCest.php
  tests/codeception/acceptance/Contrib/ConfigReadonlyCest.php
  tests/codeception/acceptance/LocalFooterCest.php
  tests/codeception/acceptance/Paragraphs/BannerCest.php
  tests/codeception/acceptance/Paragraphs/Issue2901390Cest.php
  tests/codeception/acceptance/Paragraphs/MediaWithCaptionCest.php
  tests/codeception/acceptance/SubThemeCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/acceptance/TextFormatsCest.php
  tests/codeception/acceptance/Users/DefaultUsersCest.php
  tests/codeception/acceptance/Users/RolesCest.php
  tests/codeception/functional/OpportunitiesFilterCest.php
  tests/codeception/functional/Paragraphs/WYSIWYG.html
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
  tests/codeception/functional/Paragraphs/logo.jpg
  tests/codeception/functional/Paragraphs/test.txt
  tests/src/Unit/Config/ConfigOverridesTest.php
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/src/Components/Filters.jsx
  themes/cardinal_service/pdb_components/opportunities_list/src/Components/SelectList.jsx
Labels: size/l
