Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2020-09, with the labels that each got.

#110 CSD-389 Removed link from filtered opportunity footer view
  config/sync/core.entity_form_display.paragraph.cs_opportunity_list.default.yml
  config/sync/core.entity_view_display.paragraph.cs_opportunity_list.default.yml
  config/sync/field.field.paragraph.cs_opportunity_list.su_opp_list_link.yml
  config/sync/field.storage.paragraph.su_opp_list_link.yml
  config/sync/views.view.su_opportunities.yml
Labels: size/xs

#103 CSD-380 Add resource field validation
  cardinal_service_profile.inc
  src/Plugin/Validation/Constraint/ResourceFields.php
  src/Plugin/Validation/Constraint/ResourceFieldsValidator.php
  tests/src/Unit/Plugin/Validation/Constraint/ResourceFieldsValidatorTest.php
Labels: size/s

#111 CSD-275 Updated help documentation
  help/custom-number-list.md
  help/hero-overlay.md
  help/minimal-cards.md
  help/resources.md
  help/spotlight.md
  help/table.md
  help/wysiwyg-card.md
Labels: size/xs

#113 CSD-275 Updated Opportunities documentation
  help/opportunities.md
Labels: size/xs

#115 CSD-410 Updates from September QA/Style bugs
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
Labels: size/xs

#116 Configure the view and api to use nesting of taxonomy terms
  config/sync/views.view.su_opportunities.yml
  modules/cardinal_service_rest/src/Plugin/rest/resource/TermsUsedResource.php
  themes/cardinal_service/pdb_components/Components/Filters.jsx
  themes/cardinal_service/pdb_components/Components/SelectList.jsx
  themes/cardinal_service/pdb_components/Components/Slugs.jsx
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/package.json
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
Labels: size/s

#118 CSD-401 Added main body content styles to Opportunity and Spotlight page
  config/sync/core.entity_view_display.node.su_spotlight.default.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/lib/scss/spotlight/_spotlight-view.scss
  themes/cardinal_service/lib/scss/spotlight/_spotlight.scss
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
Labels: size/s

#119 CSD-427 Updated styled and config based on QA from Sep 4-9
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  config/sync/editor.editor.stanford_html.yml
  help/table.md
  tests/codeception/acceptance/Content/SpotlightContentCest.php
  tests/codeception/acceptance/OpportunityContentCest.php
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/ckeditor.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/spotlight/_spotlight-view.scss
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
  themes/cardinal_service/lib/scss/utilities/_colors.scss
  themes/cardinal_service/lib/scss/utilities/_cta.scss
  themes/cardinal_service/lib/scss/wysiwyg/_table.scss
Labels: size/s

#121 CSD-440 Created duration range block view for opportunity content type
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  config/sync/views.view.su_opportunities.yml
  modules/cardinal_service_profile_helper/src/Form/CsvImporterForm.php
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
Labels: size/m

#117 CSD-404 Update Opportunities list and filter results text to span 10 cols
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/pdb_components/Components/Filters.jsx
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/src/app.jsx
  themes/cardinal_service/pdb_components/opportunities_list/src/styles.scss
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
Labels: size/s

#120 Added related stories list to the bottom of stories pages
  config/sync/core.entity_view_display.node.su_spotlight.default.yml
  config/sync/views.view.su_spotlights.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
  themes/cardinal_service/package.json
Labels: size/s

#122 CSD-465 Updates from September 9 QA session
  config/sync/views.view.cs_resources.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/spotlight/_spotlight-view.scss
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
Labels: size/s

#123 CSD-442 Added conditional check to add "," and "in"
  composer.json
  themes/cardinal_service/cardinal_service.theme
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/js/cardinal_service.js
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
Labels: size/xs

#124 CSD-471 Updated Our Stories layout and styles for responsiveness
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/src/app.jsx
  themes/cardinal_service/pdb_components/stories/src/styles.scss
Labels: size/s

#126 CSD-470 Added margin bottom spacing to the opportunities list page
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
Labels: size/xs

#127 CSD-468 Added breadcrumbs styles and exported configurations
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  config/sync/core.entity_view_display.node.su_spotlight.default.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/base.scss
  themes/cardinal_service/lib/scss/breadcrumbs/breadcrumbs.scss
  themes/cardinal_service/lib/scss/breadcrumbs/index.scss
  themes/cardinal_service/lib/scss/spotlight/_spotlight.scss
  themes/cardinal_service/lib/scss/utilities/_colors.scss
Labels: size/xs

#128 CSD-473 Added opportunity program, updated twig template and config
  config/sync/core.entity_view_display.node.su_opportunity.su_opportunities_views_result.yml
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.ui_patterns.yml
Labels: size/xs

#129 Render and strip tags via php instead of twig
  config/sync/field.field.node.su_spotlight.su_spotlight_quote.yml
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.install
  themes/cardinal_service/cardinal_service.theme
  themes/cardinal_service/templates/patterns/pattern-quote.html.twig
Labels: size/xs

#130 CSD-000 Update breadcrumbs and opportunity spacing
  tests/codeception/functional/OpportunitiesFilterCest.php
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/scss/breadcrumbs/breadcrumbs.scss
  themes/cardinal_service/lib/scss/utilities/_colors.scss
Labels: size/xs

#131 Stanford profile updates
  config/sync/core.entity_form_display.media.embeddable.default.yml
  config/sync/core.entity_form_display.media.embeddable.media_library.yml
  config/sync/core.entity_view_display.media.embeddable.default.yml
  config/sync/core.entity_view_display.media.embeddable.media_library.yml
  config/sync/field.field.media.embeddable.field_media_embeddable_code.yml
  config/sync/field.field.media.embeddable.field_media_embeddable_oembed.yml
  config/sync/field.storage.media.field_media_embeddable_code.yml
  config/sync/field.storage.media.field_media_embeddable_oembed.yml
  config/sync/media.type.embeddable.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/user.role.site_builder.yml
  config/sync/user.role.site_developer.yml
  config/sync/user.role.site_editor.yml
  config/sync/user.role.site_manager.yml
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Media/MediaPermissionsCest.php
  tests/codeception/acceptance/MediaCest.php
Labels: size/s

#132 CSD-474 Resolve comma spacing
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
Labels: size/xs

#134 CSD-477 Removed duration block and unlink sponsor terms
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
Labels: size/xs

#135 Release 8.1.5
  CHANGELOG.md
  cardinal_service_profile.inc
  cardinal_service_profile.info.yml
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
Labels: patch, size/xs

#136 CSD-480 Updated sponsor display title
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
Labels: size/xs

#137 CSD-484 Updated pixel height of user-links name
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/favorite/_user-links.scss
Labels: frontend, size/xs

#142 CSD-488 Exported full layout config for Basic pages
  config/sync/layout_library.layout.stanford_basic_page_full.yml
Labels: size/xs

#140 CSD-486 Add Favorites for resources
  cardinal_service_profile.inc
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.user.user.default.yml
  config/sync/flag.flag.cs_resources.yml
  config/sync/layout_library.layout.stanford_basic_page_full.yml
  config/sync/page_manager.page.saved_resources.yml
  config/sync/page_manager.page_variant.saved_resources-layout_builder-0.yml
  config/sync/system.action.flag_action.cs_resources_flag.yml
  config/sync/system.action.flag_action.cs_resources_unflag.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/views.view.cs_resources.yml
  themes/cardinal_service/cardinal_service.libraries.yml
  themes/cardinal_service/cardinal_service.theme
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/ckeditor.css
  themes/cardinal_service/dist/css/resources.css
  themes/cardinal_service/lib/scss/base.scss
  themes/cardinal_service/lib/scss/favorite/_dashboard.scss
  themes/cardinal_service/lib/scss/resources.scss
  themes/cardinal_service/lib/scss/resources/_favorites.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/resources/index.scss
  themes/cardinal_service/lib/scss/wysiwyg/_buttons.scss
  themes/cardinal_service/lib/scss/wysiwyg/_headings.scss
  themes/cardinal_service/lib/scss/wysiwyg/_list.scss
  themes/cardinal_service/lib/scss/wysiwyg/_paragraph.scss
  themes/cardinal_service/lib/scss/wysiwyg/_table.scss
  themes/cardinal_service/lib/scss/wysiwyg/_wysiwyg.scss
  themes/cardinal_service/lib/scss/wysiwyg/index.scss
  themes/cardinal_service/templates/page.html.twig
  themes/cardinal_service/webpack.config.js
Labels: frontend, size/l

#141 CSD-482 Added summary styles for opportunities list
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
Labels: frontend, size/s

#143 CSD-000 Bugherd Fixup for 09/24/2020
  config/sync/core.entity_view_display.node.su_opportunity.su_opportunities_views_result.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/resources.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/utilities/_cta.scss
Labels: frontend, size/xs

#145 8.1.7
  CHANGELOG.md
  cardinal_service_profile.info.yml
  config/sync/node_revision_delete.settings.yml
  themes/cardinal_service/pdb_components/Components/Filters.jsx
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
Labels: frontend, patch, size/s

#146 CSD-499 Resolve user links and filter styling issue on Safari
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/favorite/_user-links.scss
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_homepage/src/styles.scss
Labels: frontend, size/xs
