Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2020-08, with the labels that each got.

#72 CSD-276 Updated individual opportunity page styles
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  config/sync/core.entity_view_display.node.su_spotlight.default.yml
  config/sync/views.view.su_spotlights.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/spotlight-quote/spotlight_quote.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
Labels: size/s

#76 CSD-300 Fixed width and color issues
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/utilities/_colors.scss
Labels: size/xs

#73 CSD-277 Updated spotlight/story styles
  config/sync/core.entity_view_display.node.su_spotlight.default.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/scss/spotlight/_spotlight-view.scss
  themes/cardinal_service/lib/scss/spotlight/_spotlight.scss
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
  themes/cardinal_service/lib/scss/spotlight/index.scss
  themes/cardinal_service/lib/scss/utilities/_links.scss
  themes/cardinal_service/lib/scss/utilities/index.scss
  themes/cardinal_service/templates/patterns/pattern-quote.html.twig
Labels: size/s

#84 Updates from stanford_profile
  config/sync/config_pages.type.lockup_settings.yml
  config/sync/core.entity_form_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_1.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_2.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_3.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_4.yml
  config/sync/field.field.config_pages.lockup_settings.su_line_5.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_enabled.yml
  config/sync/field.field.config_pages.lockup_settings.su_lockup_options.yml
  config/sync/field.field.config_pages.lockup_settings.su_upload_logo_image.yml
  config/sync/field.field.config_pages.lockup_settings.su_use_theme_logo.yml
  config/sync/field.storage.config_pages.su_line_1.yml
  config/sync/field.storage.config_pages.su_line_2.yml
  config/sync/field.storage.config_pages.su_line_3.yml
  config/sync/field.storage.config_pages.su_line_4.yml
  config/sync/field.storage.config_pages.su_line_5.yml
  config/sync/field.storage.config_pages.su_lockup_enabled.yml
  config/sync/field.storage.config_pages.su_lockup_options.yml
  config/sync/field.storage.config_pages.su_upload_logo_image.yml
  config/sync/field.storage.config_pages.su_use_theme_logo.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/stanford_basic.settings.yml
  config/sync/user.role.site_manager.yml
  config/sync/views.view.content.yml
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsCest.php
  tests/codeception/acceptance/LockupSettings/LockupSettingsPermsCest.php
  tests/codeception/acceptance/LockupSettings/logo.jpg
Labels: size/l

#85 CSD-300 Resource library card styles
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
Labels: size/xs

#81 CSD-299 August 5 QA Fixes
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/minimal-card/minimal_card.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/minimal-card/minimal_card.scss
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/scss/favorite/_dashboard.scss
  themes/cardinal_service/lib/scss/favorite/_user-links.scss
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/lib/scss/utilities/_buttons.scss
  themes/cardinal_service/lib/scss/utilities/_cta.scss
  themes/cardinal_service/lib/scss/utilities/_pager.scss
  themes/cardinal_service/lib/scss/utilities/index.scss
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_homepage/src/styles.scss
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
Labels: size/s

#86 CSD-000 Moved filters styles into its own file and adjusted Stories filter background color
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
  themes/cardinal_service/pdb_components/Components/Filters.jsx
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/resources/src/styles.scss
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/src/styles.scss
Labels: size/xs

#87 CSD-201 Style Bug Fixes
  config/sync/views.view.cs_resources.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/pdb_components/Components/Filters.jsx
  themes/cardinal_service/pdb_components/Components/SelectList.jsx
  themes/cardinal_service/pdb_components/Components/Slugs.jsx
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/src/app.jsx
  themes/cardinal_service/pdb_components/opportunities_list/src/styles.scss
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/resources/src/styles.scss
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/src/styles.scss
Labels: size/s

#88 CSD-269 improve csv Importer
  composer.json
  config/sync/core.extension.yml
  config/sync/migrate_plus.migration.csv_opportunities.yml
  config/sync/migrate_plus.migration.csv_spotlight.yml
  config/sync/migrate_plus.migration_group.csv_importers.yml
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.links.menu.yml
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.module
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.routing.yml
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.services.yml
  modules/cardinal_service_profile_helper/src/Controller/NodeCsvTemplate.php
  modules/cardinal_service_profile_helper/src/Form/CsvImporterForm.php
  modules/cardinal_service_profile_helper/src/Routing/RouteSubscriber.php
  modules/cardinal_service_profile_helper/tests/src/Kernel/Controller/NodeCsvTemplateTest.php
  modules/cardinal_service_profile_helper/tests/src/Kernel/Form/CsvImporterFormTest.php
  modules/cardinal_service_profile_helper/tests/src/Kernel/Routing/RouteSubscriberTest.php
  tests/codeception/acceptance/Content/SpotlightContentCest.php
Labels: size/l

#89 Added back to top link and animation
  themes/cardinal_service/cardinal_service.libraries.yml
  themes/cardinal_service/cardinal_service.theme
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/js/cardinal_service.js
  themes/cardinal_service/lib/scss/_backtotop.scss
  themes/cardinal_service/lib/scss/base.scss
Labels: size/xs

#90 CSD-202 Style fixes
  config/sync/views.view.su_opportunities.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/scss/favorite/_dashboard.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
  themes/cardinal_service/lib/scss/utilities/_hero.scss
  themes/cardinal_service/pdb_components/Components/Filters.jsx
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_homepage/lib/app.js.map
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js
  themes/cardinal_service/pdb_components/opportunities_list/lib/app.js.map
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
Labels: size/xs

#91 CSD-278 Styled number list
  config/sync/editor.editor.stanford_html.yml
  config/sync/filter.format.stanford_html.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/ckeditor.css
  themes/cardinal_service/lib/scss/base.scss
  themes/cardinal_service/lib/scss/ckeditor.scss
  themes/cardinal_service/lib/scss/utilities/_colors.scss
  themes/cardinal_service/lib/scss/wysiwyg/_list.scss
  themes/cardinal_service/lib/scss/wysiwyg/index.scss
Labels: size/xs

#93 CSD-347 Fixed user-links responsive styles
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/favorite/_user-links.scss
Labels: size/xs

#96 CSD-358 Updated individual spotlight stories spacing
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/spotlight/_spotlight.scss
Labels: size/xs

#95 CSD-327 Added 1/4 Table WYSWYG Style
  config/sync/editor.editor.stanford_html.yml
  config/sync/filter.format.stanford_html.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/ckeditor.css
  themes/cardinal_service/lib/scss/wysiwyg/_table.scss
  themes/cardinal_service/lib/scss/wysiwyg/index.scss
Labels: size/xs

#97 CSD-363 Updated cta text within spotlight view
  config/sync/views.view.su_spotlights.yml
Labels: size/xs

#98 CSD-359 Updated related opportunity view and styles
  config/sync/views.view.su_opportunities.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
Labels: size/xs

#99 CSD-000 Updated yellow number list
  config/sync/editor.editor.stanford_html.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/ckeditor.css
  themes/cardinal_service/lib/scss/wysiwyg/_list.scss
Labels: size/xs

#101 Added padding around spotlight inline images
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/spotlight/_spotlight.scss
Labels: size/xs

#105 CSD-368 Hid ajax loader display to prevent visual shifting.
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/favorite/_flag.scss
Labels: size/xs

#100 Added a help section with contents of the help documents
  README.md
  composer.json
  help/opportunities.md
  help/spotlight.md
  modules/cardinal_service_profile_helper/cardinal_service_profile_helper.routing.yml
  modules/cardinal_service_profile_helper/src/Controller/Documentation.php
  modules/cardinal_service_profile_helper/tests/src/Kernel/Controller/DocumentationTest.php
  src/Plugin/HelpSection/CardinalServiceSection.php
  tests/src/Unit/Plugin/HelpSection/CardinalServiceSectionTest.php
Labels: size/s

#106 CSD-387 Updated spotlight list and filter styles
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
  themes/cardinal_service/pdb_components/package-lock.json
  themes/cardinal_service/pdb_components/resources/lib/app.js
  themes/cardinal_service/pdb_components/resources/lib/app.js.map
  themes/cardinal_service/pdb_components/resources/src/app.jsx
  themes/cardinal_service/pdb_components/stories/lib/app.js
  themes/cardinal_service/pdb_components/stories/lib/app.js.map
  themes/cardinal_service/pdb_components/stories/src/app.jsx
  themes/cardinal_service/pdb_components/stories/src/styles.scss
Labels: size/l

#102 CSD-362 Updated opportunity row and page
  composer.json
  config/sync/core.entity_view_display.node.su_opportunity.default.yml
  config/sync/core.entity_view_display.node.su_opportunity.su_opportunities_views_result.yml
  config/sync/views.view.cs_resources.yml
  config/sync/views.view.su_opportunities.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/components/opportunity-row/opportunity_row.css
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.html.twig
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.scss
  themes/cardinal_service/lib/components/opportunity-row/opportunity_row.ui_patterns.yml
  themes/cardinal_service/lib/scss/opportunities/_opportunities.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/spotlight/_spotlight-view.scss
Labels: size/s

#104 CSD-375 set up equal height cards and view items
  config/sync/views.view.cs_resources.yml
  config/sync/views.view.su_spotlights.yml
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/lib/scss/_paragraphs.scss
  themes/cardinal_service/lib/scss/base.scss
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/lib/scss/spotlight/_stories.scss
Labels: size/xs

#109 CSD-397 Adjusted table to be vertically top aligned
  themes/cardinal_service/dist/css/base.css
  themes/cardinal_service/dist/css/ckeditor.css
  themes/cardinal_service/lib/scss/wysiwyg/_table.scss
Labels: size/xs

#108 CSD-000 Excluded Page title block from events
  config/sync/block.block.cardinal_service_pagetitle.yml
Labels: size/xs
