Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2021-03, with the labels that each got.

#165 8.1.13
  CHANGELOG.md
  cardinal_service_profile.info.yml
  composer.json
  config/sync/migrate_plus.migration.cardcourses_law.yml
  themes/cardinal_service/dist/css/resources.css
  themes/cardinal_service/lib/scss/resources/_resource-library.scss
  themes/cardinal_service/package.json
Labels: frontend, patch, size/xs

#167 Updates from stanford_profile
  config/sync/core.entity_view_display.taxonomy_term.stanford_publication_topics.default.yml
  config/sync/field.field.paragraph_row.su_pub_rows.su_pubs_components.yml
  config/sync/views.view.publication_terms.yml
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#168 Updates from stanford_profile
  config/sync/views.view.stanford_publications.yml
Labels: size/xs

#169 8.1.14
  CHANGELOG.md
  cardinal_service_profile.info.yml
  config/sync/migrate_plus.migration.cardcourses_socioecon.yml
Labels: patch, size/xs
