Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2022-07, with the labels that each got.

#279 8.3.3
  .circleci/config.yml
  .github/workflows/tests.yml
  CHANGELOG.md
  cardinal_service_profile.info.yml
  composer.json
  config/sync/core.entity_view_display.config_pages.lockup_settings.default.yml
  config/sync/core.entity_view_display.media.embeddable.media_library.yml
  config/sync/core.entity_view_display.media.file.media_library.yml
  config/sync/core.entity_view_display.media.google_form.media_library.yml
  config/sync/core.entity_view_display.media.image.media_library.yml
  config/sync/core.entity_view_display.media.image.stanford_image_large.yml
  config/sync/core.entity_view_display.media.image.stanford_image_large_square.yml
  config/sync/core.entity_view_display.media.image.stanford_image_medium.yml
  config/sync/core.entity_view_display.media.image.stanford_image_medium_square.yml
  config/sync/core.entity_view_display.media.image.stanford_image_stanford_circle.yml
  config/sync/core.entity_view_display.media.image.stanford_image_thumb_square.yml
  config/sync/core.entity_view_display.media.image.thumbnail.yml
  config/sync/core.entity_view_display.media.stanford_gallery_images.media_library.yml
  config/sync/core.entity_view_display.media.video.media_library.yml
  config/sync/core.extension.yml
  config/sync/editor.editor.stanford_minimal_html.yml
  config/sync/field.field.media.embeddable.field_media_embeddable_code.yml
  config/sync/filter.format.stanford_html.yml
  config/sync/filter.format.stanford_minimal_html.yml
  config/sync/jsonapi.settings.yml
  config/sync/media.type.embeddable.yml
  config/sync/views.view.media.yml
  config/sync/views.view.media_library.yml
  config/sync/views.view.search.yml
  config/sync/views.view.stanford_courses.yml
  config/sync/views.view.taxonomy_term_pages.yml
  modules/cardinal_service_rest/cardinal_service_rest.info.yml
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/BasicPage/BasicPageParagraphsCest.php
  tests/codeception/functional/Paragraphs/BannerCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
  tests/codeception/functional/Paragraphs/GalleryCest.php
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
  tests/src/Unit/Plugin/Validation/Constraint/ResourceFieldsValidatorTest.php
  themes/cardinal_service/cardinal_service.info.yml
Labels: size/xs, patch

#280 Updates from stanford_profile
  config/sync/oembed_providers.provider.sul_embed_service.yml
  config/sync/views.view.content.yml
  tests/codeception/acceptance/Media/MediaCest.php
Labels: size/xs, backend

#282 Updates from stanford_profile
  config/sync/core.entity_form_display.node.stanford_course.default.yml
  config/sync/core.entity_form_display.node.stanford_page.default.yml
  config/sync/views.view.stanford_courses.yml
Labels: size/s
