Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2022-05, with the labels that each got.

#253 Stanford Profile 8.4.4 Updates
  cardinal_service_profile.services.yml
  config/sync/config_pages.type.stanford_basic_site_settings.yml
  config/sync/core.entity_form_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/core.entity_view_display.config_pages.stanford_basic_site_settings.default.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_403.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_404.yml
  config/sync/field.field.config_pages.stanford_basic_site_settings.su_site_home.yml
  config/sync/field.field.paragraph.stanford_media_caption.su_media_caption_caption.yml
  config/sync/field.storage.config_pages.su_site_403.yml
  config/sync/field.storage.config_pages.su_site_404.yml
  config/sync/field.storage.config_pages.su_site_home.yml
  config/sync/migrate_plus.migration.stanford_course_depts.yml
  config/sync/migrate_plus.migration.stanford_courses.yml
  config/sync/user.role.anonymous.yml
  config/sync/user.role.authenticated.yml
  config/sync/views.view.stanford_courses.yml
  config/sync/views.view.taxonomy_term_pages.yml
  tests/codeception/acceptance/LocalFooter/LocalFooterCest.php
  tests/codeception/acceptance/LocalFooter/LocalFooterLockupCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Paragraphs/ListsCest.php
  tests/codeception/acceptance/SystemSiteConfigCest.php
  tests/codeception/functional/Contrib/ExtLinkCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
Labels: size/m, backend

#254 Changed Events page menu block.
  config/sync/page_manager.page_variant.stanford_events_upcoming-layout_builder-0.yml
Labels: size/xs

#257 CS-86: Drop event opportunities
  config/sync/core.entity_view_display.node.stanford_course.default.yml
  config/sync/core.entity_view_display.node.stanford_page.default.yml
  config/sync/core.entity_view_display.node.stanford_page.search_indexing.yml
  config/sync/core.entity_view_display.node.stanford_page.stanford_card.yml
  config/sync/core.entity_view_display.node.su_opportunity.su_opportunities_grid_result.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_event_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_news_topics.default.yml
  config/sync/core.entity_view_display.taxonomy_term.stanford_person_types.default.yml
  config/sync/core.entity_view_display.taxonomy_term.su_course_quarters.default.yml
  config/sync/core.entity_view_display.taxonomy_term.su_course_subjects.default.yml
  config/sync/migrate_plus.migration.cs_events_importer.yml
  config/sync/migrate_plus.migration.stanford_courses.yml
  config/sync/page_manager.page_variant.courses_list_page-layout_builder-0.yml
  config/sync/views.view.su_opportunities.yml
Labels: size/xs

#261 Change the branch to pull from for 8.x branch
  .circleci/config.yml
Labels: size/xs, ci
