Repository SU-HKKU/cardinal_service_profile, pull requests merged in 2024-09, with the labels that each got.

#326 CS-128 - change order - contact and CTA button
  config/sync/core.entity_view_display.node.su_opportunity.cardinal_quarter_grid_results.yml
  modules/cardinal_service_profile_helper/dist/components/cardinal-quarter-grid/cardinal_quarter.css
  modules/cardinal_service_profile_helper/dist/components/minimal-card/minimal_card.css
  modules/cardinal_service_profile_helper/dist/components/mission-statement/mission_statement.css
  modules/cardinal_service_profile_helper/dist/components/opportunity-grid/opportunity_grid.css
  modules/cardinal_service_profile_helper/dist/components/opportunity-row/opportunity_row.css
  modules/cardinal_service_profile_helper/package.json
  modules/cardinal_service_profile_helper/templates/components/cardinal-quarter-grid/cardinal_quarter.scss
  modules/cardinal_service_profile_helper/templates/components/cardinal-quarter-grid/cardinal_quarter_grid.html.twig
  modules/cardinal_service_profile_helper/templates/components/cardinal-quarter-grid/cardinal_quarter_grid.ui_patterns.yml
  modules/cardinal_service_profile_helper/yarn.lock
Labels: size/l, frontend

#329 fix inheritance
  cardinal_service_profile.services.yml
  composer.json
  config/sync/core.extension.yml
  src/EventSubscriber/EventSubscriber.php
  src/Plugin/InstallTask/SiteSettings.php
  tests/codeception/acceptance/AuthenticatedPermissionsCest.php
  tests/codeception/acceptance/Content/DefaultContentCest.php
  tests/codeception/acceptance/Content/EventsCest.php
  tests/codeception/acceptance/Content/NewsCest.php
  tests/codeception/acceptance/Content/OpportunityCest.php
  tests/codeception/acceptance/Content/PersonCest.php
  tests/codeception/acceptance/Contrib/ViewsBulkEditCest.php
  tests/codeception/acceptance/Contrib/XmlsitemapCest.php
  tests/codeception/acceptance/Media/MediaCest.php
  tests/codeception/acceptance/Paragraphs/TeaserCest.php
  tests/codeception/acceptance/SubThemeCest.php
  tests/codeception/acceptance/Users/IntranetCest.php
  tests/codeception/functional/Paragraphs/EntityReferenceCest.php
  tests/codeception/functional/Paragraphs/WYSIWYGCest.php
Labels: size/xs, backend

#330 Check fo tables to delete
  cardinal_service_profile.install
Labels: size/xs
